services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./test_images:/test_images
    networks:
      - data_network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    command: ["--listen_host=0.0.0.0"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - data_network

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - data_network
    environment:
      GF_INSTALL_PLUGINS: "vertamedia-clickhouse-datasource"
    depends_on:
      - clickhouse

  python-service:
    build: ./python-microservice
    depends_on:
      mosquitto:
        condition: service_started
      clickhouse:
        condition: service_started
    networks:
      - data_network

networks:
  data_network:
    name: flowforge_data_network
    driver: bridge

volumes:
  clickhouse_data:
  grafana_data: