# MediaMTX Configuration
api: yes
apiAddress: 0.0.0.0:9997

metrics: yes
metricsAddress: 0.0.0.0:9998

pprof: no

logLevel: info
logDestinations: [stdout]

rtspAddress: :8554
rtmpAddress: :1935
hlsAddress: :8888
webrtcAddress: :8889

paths:
  # Stream from test video file  
  test:
    source: publisher
    
  # Stream from webcam (if available)
  webcam:
    source: publisher
    
  # Example with file streaming
  video1:
    source: file:///test_videos/sample.mp4
    sourceOnDemand: yes
    
  # Another video stream
  video2:
    source: publisher

