paths:
  test:
    runOnInit: ffmpeg -re -stream_loop -1 -i /test_videos/sample.mp4 -c:v copy -c:a copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1:8554/test
    runOnInitRestart: yes
  video1:
    runOnInit: ffmpeg -re -stream_loop -1 -i /test_videos/sample.mp4 -c:v copy -c:a copy -f rtsp -rtsp_transport tcp rtsp://127.0.0.1:8554/video1
    runOnInitRestart: yes

api: yes
apiAddress: :9997
metrics: yes
metricsAddress: :9998
pprof: no
logLevel: debug
logDestinations: [stdout]
rtspAddress: :8554
rtmpAddress: :1935
hlsAddress: :8888
webrtcAddress: :8889
