apiVersion: 1

datasources:
- name: ClickHouse
  type: vertamedia-clickhouse-datasource
  access: proxy
  url: http://clickhouse:8123
  jsonData:
    server: clickhouse
    port: 9000
    username: "default"
    password: "password"
    defaultDatabase: default
    connectTimeout: 30
    queryTimeout: 60
  secureJsonData:
    # Если требуется шифрованное хранение пароля
    password: "password"
  editable: true