apiVersion: 1

datasources:
  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      server: clickhouse
      port: 9000
      username: default
      defaultDatabase: default
    editable: true